name: Backend CI/CD with Docker Hub and Render

on:
  push:
    branches:
      - master
      - "feature/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore BooksChanger/BooksChanger.csproj

      - name: List files for debugging
        run: ls -R BooksChanger

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/book-changer-back:latest -f BooksChanger/Dockerfile .

      - name: Push Docker Image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/book-changer-back:latest

      - name: Install Render CLI
        run: curl -fsSL https://render.com/static/cli/install.sh | bash

      - name: Install Terraform
        run: sudo apt-get update && sudo apt-get install -y terraform

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        run: terraform apply -auto-approve

      - name: Verify API availability
        run: |
          sleep 30
          curl -s -o /dev/null -w "%{http_code}" https://bookchangerbackend.onrender.com/health \
            | grep 200 || (echo "API is unavailable!" && exit 1)
