name: Backend CI/CD with Docker Hub and Render

on:
  push:
    branches:
      - master
      - "feature/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore BooksChanger/BooksChanger.csproj

      - name: Run tests
        run: dotnet test

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/book-changer-back:latest -f BooksChanger/Dockerfile .

      - name: Push Docker Image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/book-changer-back:latest

      - name: Install Render CLI
        run: curl -fsSL https://render.com/static/cli/install.sh | bash

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services update srv-ctdbhdjqf0us73bo4tig \
            --env-vars TOKEN=${{ secrets.TOKEN }} DB_CONNECTION=${{ secrets.DB_CONNECTION }}
